' Gambas module file

PUBLIC SUB Main()
DIM MyProc AS Process
DIM Ret AS String

IF System.User.Id <> 0 THEN
   EXEC ["which", "kdesu"] TO Ret
   IF InStr(Ret, "kdesu") THEN
      EXEC ["kdesu", "vl-hot-config.gambas"]
   ELSE
      EXEC ["which", "gksu"] TO Ret
      IF InStr(Ret, "gksu") THEN
         EXEC ["gksu", "vl-hot-config.gambas"]
      ELSE
         PRINT "No kdesu or gksu available (vl-hot-config needs to run as root)..."
      ENDIF
   ENDIF
   QUIT

'IF System.User.Name <> "root" THEN
'   message.Warning("You need to be root to run " & Application.Title & gb.NewLine & "Starting in read-only mode...")
ELSE
   FMain.butWrite.Enabled = TRUE
   FMain.txtMOUNTPATH.ReadOnly = FALSE
   FMain.tbtMountbase.Enabled = TRUE
   FMain.txtICON.ReadOnly = FALSE
   FMain.tbtIcon.Enabled = TRUE
   FMain.noatime.Enabled = TRUE
   FMain.exec.Enabled = TRUE
   FMain.sync.Enabled = TRUE
   FMain.dirsync.Enabled = TRUE
   FMain.txtExclude.ReadOnly = FALSE
   FMain.txtInclude.ReadOnly = FALSE
   FMain.rbtDiagON.Enabled = TRUE
   FMain.rbtDiagOFF.Enabled = TRUE
   FMain.NTFSro.Enabled = TRUE
   FMain.NTFS3g.Enabled = TRUE
   FMain.cmbFATcodepage.Enabled = TRUE
   FMain.cmbFATcharsets.Enabled = TRUE
   FMain.cmbNTFSnls.Enabled = TRUE
   FMain.chkSounds.Enabled = TRUE
   FMain.tbtSuccess.Enabled = TRUE
   FMain.tbtError.Enabled = TRUE
   FMain.txtCustomMountPoints.Enabled = TRUE
   FMain.butNamesSave.Enabled = TRUE
   FMain.butNamesRestore.Enabled = TRUE
ENDIF

FMain.Show

END
